# Codecov configuration
# Docs: https://docs.codecov.io/docs/codecov-yaml
codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 1%
    patch:
      default:
        target: 85%

comment:
  layout: "reach,diff,flags,components"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

flags:
  unit:
    paths:
      - src/
    carryforward: false
  nightly:
    paths:
      - src/
    carryforward: true
