import { defineConfig } from 'vitest/config';
import path from 'path';

export default defineConfig({
  test: {
    globals: true,
    environment: 'node',
    include: ['tests/**/*.test.js'],
    setupFiles: ['tests/setup.js'],
  },
  resolve: {
    alias: {
      // Wix platform mocks
      'wix-web-module': path.resolve(__dirname, 'tests/__mocks__/wix-web-module.js'),
      'wix-data': path.resolve(__dirname, 'tests/__mocks__/wix-data.js'),
      'wix-crm-backend': path.resolve(__dirname, 'tests/__mocks__/wix-crm-backend.js'),
      'wix-secrets-backend': path.resolve(__dirname, 'tests/__mocks__/wix-secrets-backend.js'),
      'wix-fetch': path.resolve(__dirname, 'tests/__mocks__/wix-fetch.js'),
      'wix-members-backend': path.resolve(__dirname, 'tests/__mocks__/wix-members-backend.js'),
      'wix-storage-frontend': path.resolve(__dirname, 'tests/__mocks__/wix-storage-frontend.js'),
      'wix-stores-frontend': path.resolve(__dirname, 'tests/__mocks__/wix-stores-frontend.js'),
      'wix-location-frontend': path.resolve(__dirname, 'tests/__mocks__/wix-location-frontend.js'),
      'wix-location': path.resolve(__dirname, 'tests/__mocks__/wix-location.js'),
      'wix-window-frontend': path.resolve(__dirname, 'tests/__mocks__/wix-window-frontend.js'),
      'wix-crm-frontend': path.resolve(__dirname, 'tests/__mocks__/wix-crm-frontend.js'),
      'wix-members-frontend': path.resolve(__dirname, 'tests/__mocks__/wix-members-frontend.js'),
      'wix-site-frontend': path.resolve(__dirname, 'tests/__mocks__/wix-site-frontend.js'),
      'wix-crm': path.resolve(__dirname, 'tests/__mocks__/wix-crm.js'),
      'wix-ecom-backend': path.resolve(__dirname, 'tests/__mocks__/wix-ecom-backend.js'),
      'wix-loyalty.v2': path.resolve(__dirname, 'tests/__mocks__/wix-loyalty.v2.js'),
      'wix-marketing-backend': path.resolve(__dirname, 'tests/__mocks__/wix-marketing-backend.js'),
      'wix-http-functions': path.resolve(__dirname, 'tests/__mocks__/wix-http-functions.js'),
      'wix-media-backend': path.resolve(__dirname, 'tests/__mocks__/wix-media-backend.js'),
      // Backend modules
      'backend/ups-shipping.web': path.resolve(__dirname, 'src/backend/ups-shipping.web.js'),
      'backend/productRecommendations.web': path.resolve(__dirname, 'src/backend/productRecommendations.web.js'),
      'backend/seoHelpers.web': path.resolve(__dirname, 'src/backend/seoHelpers.web.js'),
      'backend/swatchService.web': path.resolve(__dirname, 'src/backend/swatchService.web.js'),
      'backend/emailService.web': path.resolve(__dirname, 'src/backend/emailService.web.js'),
      'backend/emailAutomation.web': path.resolve(__dirname, 'src/backend/emailAutomation.web.js'),
      'backend/cartRecovery.web': path.resolve(__dirname, 'src/backend/cartRecovery.web.js'),
      'backend/contactSubmissions.web': path.resolve(__dirname, 'src/backend/contactSubmissions.web.js'),
      'backend/promotions.web': path.resolve(__dirname, 'src/backend/promotions.web.js'),
      'backend/analyticsHelpers.web': path.resolve(__dirname, 'src/backend/analyticsHelpers.web.js'),
      'backend/dataService.web': path.resolve(__dirname, 'src/backend/dataService.web.js'),
      'backend/fulfillment.web': path.resolve(__dirname, 'src/backend/fulfillment.web.js'),
      'backend/googleMerchantFeed.web': path.resolve(__dirname, 'src/backend/googleMerchantFeed.web.js'),
      'backend/notificationService.web': path.resolve(__dirname, 'src/backend/notificationService.web.js'),
      'backend/testimonialService.web': path.resolve(__dirname, 'src/backend/testimonialService.web.js'),
      'backend/styleQuiz.web': path.resolve(__dirname, 'src/backend/styleQuiz.web.js'),
      'backend/searchService.web': path.resolve(__dirname, 'src/backend/searchService.web.js'),
      'backend/sizeGuide.web': path.resolve(__dirname, 'src/backend/sizeGuide.web.js'),
      'backend/liveChatService.web': path.resolve(__dirname, 'src/backend/liveChatService.web.js'),
      'backend/wishlistAlerts.web': path.resolve(__dirname, 'src/backend/wishlistAlerts.web.js'),
      'backend/inventoryService.web': path.resolve(__dirname, 'src/backend/inventoryService.web.js'),
      'backend/comparisonService.web': path.resolve(__dirname, 'src/backend/comparisonService.web.js'),
      'backend/browseAbandonment.web': path.resolve(__dirname, 'src/backend/browseAbandonment.web.js'),
      'backend/inventoryAlerts.web': path.resolve(__dirname, 'src/backend/inventoryAlerts.web.js'),
      'backend/postPurchaseCare.web': path.resolve(__dirname, 'src/backend/postPurchaseCare.web.js'),
      'backend/bundleAnalytics.web': path.resolve(__dirname, 'src/backend/bundleAnalytics.web.js'),
      'backend/seoContentHub.web': path.resolve(__dirname, 'src/backend/seoContentHub.web.js'),
      'backend/pinterestRichPins.web': path.resolve(__dirname, 'src/backend/pinterestRichPins.web.js'),
      'backend/photoReviews.web': path.resolve(__dirname, 'src/backend/photoReviews.web.js'),
      'backend/sustainability.web': path.resolve(__dirname, 'src/backend/sustainability.web.js'),
      'backend/roomPlanner.web': path.resolve(__dirname, 'src/backend/roomPlanner.web.js'),
      'backend/abTesting.web': path.resolve(__dirname, 'src/backend/abTesting.web.js'),
      'backend/coreWebVitals.web': path.resolve(__dirname, 'src/backend/coreWebVitals.web.js'),
      'backend/blogContent': path.resolve(__dirname, 'src/backend/blogContent.js'),
      'backend/utils/sanitize': path.resolve(__dirname, 'src/backend/utils/sanitize.js'),
      'backend/utils/mediaHelpers': path.resolve(__dirname, 'src/backend/utils/mediaHelpers.js'),
      'backend/utils/errorHandler': path.resolve(__dirname, 'src/backend/utils/errorHandler.js'),
      // Public modules
      'public/galleryHelpers.js': path.resolve(__dirname, 'src/public/galleryHelpers.js'),
      'public/galleryHelpers': path.resolve(__dirname, 'src/public/galleryHelpers.js'),
      'public/designTokens.js': path.resolve(__dirname, 'src/public/designTokens.js'),
      'public/designTokens': path.resolve(__dirname, 'src/public/designTokens.js'),
      'public/placeholderImages.js': path.resolve(__dirname, 'src/public/placeholderImages.js'),
      'public/placeholderImages': path.resolve(__dirname, 'src/public/placeholderImages.js'),
      'public/galleryConfig.js': path.resolve(__dirname, 'src/public/galleryConfig.js'),
      'public/galleryConfig': path.resolve(__dirname, 'src/public/galleryConfig.js'),
      'public/testProducts.js': path.resolve(__dirname, 'src/public/testProducts.js'),
      'public/testProducts': path.resolve(__dirname, 'src/public/testProducts.js'),
      'public/cartService.js': path.resolve(__dirname, 'src/public/cartService.js'),
      'public/cartService': path.resolve(__dirname, 'src/public/cartService.js'),
      'public/mobileHelpers.js': path.resolve(__dirname, 'src/public/mobileHelpers.js'),
      'public/mobileHelpers': path.resolve(__dirname, 'src/public/mobileHelpers.js'),
      'public/engagementTracker.js': path.resolve(__dirname, 'src/public/engagementTracker.js'),
      'public/engagementTracker': path.resolve(__dirname, 'src/public/engagementTracker.js'),
      'public/pwaHelpers.js': path.resolve(__dirname, 'src/public/pwaHelpers.js'),
      'public/pwaHelpers': path.resolve(__dirname, 'src/public/pwaHelpers.js'),
      'public/productCache.js': path.resolve(__dirname, 'src/public/productCache.js'),
      'public/productCache': path.resolve(__dirname, 'src/public/productCache.js'),
      'public/touchHelpers.js': path.resolve(__dirname, 'src/public/touchHelpers.js'),
      'public/touchHelpers': path.resolve(__dirname, 'src/public/touchHelpers.js'),
      'public/safeInit.js': path.resolve(__dirname, 'src/public/safeInit.js'),
      'public/safeInit': path.resolve(__dirname, 'src/public/safeInit.js'),
      'public/sharedTokens.js': path.resolve(__dirname, 'src/public/sharedTokens.js'),
      'public/sharedTokens': path.resolve(__dirname, 'src/public/sharedTokens.js'),
      'public/productPageUtils.js': path.resolve(__dirname, 'src/public/productPageUtils.js'),
      'public/productPageUtils': path.resolve(__dirname, 'src/public/productPageUtils.js'),
      'public/ProductGallery.js': path.resolve(__dirname, 'src/public/ProductGallery.js'),
      'public/ProductGallery': path.resolve(__dirname, 'src/public/ProductGallery.js'),
      'public/ProductOptions.js': path.resolve(__dirname, 'src/public/ProductOptions.js'),
      'public/ProductOptions': path.resolve(__dirname, 'src/public/ProductOptions.js'),
      'public/ProductDetails.js': path.resolve(__dirname, 'src/public/ProductDetails.js'),
      'public/ProductDetails': path.resolve(__dirname, 'src/public/ProductDetails.js'),
      'public/ProductReviews.js': path.resolve(__dirname, 'src/public/ProductReviews.js'),
      'public/ProductReviews': path.resolve(__dirname, 'src/public/ProductReviews.js'),
      'public/AddToCart.js': path.resolve(__dirname, 'src/public/AddToCart.js'),
      'public/AddToCart': path.resolve(__dirname, 'src/public/AddToCart.js'),
      'public/LiveChat.js': path.resolve(__dirname, 'src/public/LiveChat.js'),
      'public/LiveChat': path.resolve(__dirname, 'src/public/LiveChat.js'),
      'public/ReturnsPortal.js': path.resolve(__dirname, 'src/public/ReturnsPortal.js'),
      'public/ReturnsPortal': path.resolve(__dirname, 'src/public/ReturnsPortal.js'),
      'backend/returnsService.web': path.resolve(__dirname, 'src/backend/returnsService.web.js'),
      'backend/storeLocatorService.web': path.resolve(__dirname, 'src/backend/storeLocatorService.web.js'),
      'backend/bundleBuilder.web': path.resolve(__dirname, 'src/backend/bundleBuilder.web.js'),
      'backend/checkoutOptimization.web': path.resolve(__dirname, 'src/backend/checkoutOptimization.web.js'),
      'backend/sustainabilityService.web': path.resolve(__dirname, 'src/backend/sustainabilityService.web.js'),
      'backend/deliveryExperience.web': path.resolve(__dirname, 'src/backend/deliveryExperience.web.js'),
      'backend/topicClusters.web': path.resolve(__dirname, 'src/backend/topicClusters.web.js'),
      'backend/mediaGallery.web': path.resolve(__dirname, 'src/backend/mediaGallery.web.js'),
      'backend/accountDashboard.web': path.resolve(__dirname, 'src/backend/accountDashboard.web.js'),
      'backend/giftRegistry.web': path.resolve(__dirname, 'src/backend/giftRegistry.web.js'),
      'backend/paymentOptions.web': path.resolve(__dirname, 'src/backend/paymentOptions.web.js'),
      'backend/productQA.web': path.resolve(__dirname, 'src/backend/productQA.web.js'),
      'backend/catalogImport.web': path.resolve(__dirname, 'src/backend/catalogImport.web.js'),
      'backend/loyaltyTiers.web': path.resolve(__dirname, 'src/backend/loyaltyTiers.web.js'),
      'public/timeConstants.js': path.resolve(__dirname, 'src/public/timeConstants.js'),
      'public/timeConstants': path.resolve(__dirname, 'src/public/timeConstants.js'),
    },
  },
});
