/**
 * @page Shared Wishlist
 * @url /shared-wishlist
 * @description Public wishlist view page. Resolves a ?share=token URL param,
 * displays the wishlist owner's saved products, and lets visitors add items
 * to their own cart.
 *
 * Editor hookup required — see editor-hookup-guide.html for element IDs.
 *
 * CMS access is entirely via the resolveShareToken backend method.
 * This page has no direct CMS access. Collections used by the backend:
 * - WishlistShareTokens — token lookup
 * - Wishlist — member's saved products
 * - Members/FullData — owner display name
 *
 * URL params:
 * - ?share=<token> — share token generated by Member Page
 *
 * S1: Token resolution + invalid/expired states
 * S2: Wishlist rendering (owner name, item count, product cards)
 * S3: Add to cart from shared view
 * S4: (Member Page — see Member Page.js)
 * S5: SEO — dynamic title, noindex for invalid tokens
 */
import { resolveShareToken } from 'backend/wishlistShare.web';
import { announce } from 'public/a11yHelpers';
import wixLocationFrontend from 'wix-location-frontend';

// ── Page entry point ──────────────────────────────────────────────────

$w.onReady(async function () {
  await _resolveAndRender();
});

// ── Core render function (exported for testing) ───────────────────────

/**
 * Resolve the ?share token and render the page.
 * Exported so tests can invoke it directly without triggering $w.onReady.
 * @returns {Promise<void>}
 */
export async function _resolveAndRender() {
  // Show loading, hide content and error
  try { $w('#shareLoadingSection').expand(); } catch (e) {}
  try { $w('#shareContentSection').collapse(); } catch (e) {}
  try { $w('#shareErrorSection').collapse(); } catch (e) {}
  try { $w('#shareNoIndex').collapse(); } catch (e) {}

  const token = wixLocationFrontend.query?.share || null;

  if (!token) {
    _showError('Wishlist link not found. Please check the link and try again.');
    return;
  }

  try {
    const result = await resolveShareToken(token);

    if (result.error) {
      if (result.error === 'Token expired') {
        _showError('This wishlist link has expired. Ask the owner to share a new link.');
      } else {
        _showError('This wishlist link was not found. It may have been removed.');
      }
      return;
    }

    const { items, ownerName } = result;

    // ── S2: Render header ──────────────────────────────────────────
    try { $w('#shareOwnerName').text = `${ownerName}'s Wishlist`; } catch (e) {}
    try { $w('#shareItemCount').text = `${items.length} item${items.length !== 1 ? 's' : ''}`; } catch (e) {}
    try { $w('#shareMetaTitle').text = `${ownerName}'s Wishlist — Carolina Futons`; } catch (e) {}

    // ── S2: Empty state ────────────────────────────────────────────
    if (items.length === 0) {
      try { $w('#shareEmptyState').expand(); } catch (e) {}
    } else {
      try { $w('#shareEmptyState').collapse(); } catch (e) {}
    }

    // ── S2: Populate repeater ──────────────────────────────────────
    const repeater = $w('#shareRepeater');
    repeater.data = items.map(item => ({ ...item }));

    repeater.onItemReady(($item, itemData) => {
      // Product name + image
      try { $item('#shareProductName').text = itemData.productName || ''; } catch (e) {}
      try {
        if (itemData.productImage) $item('#shareProductImage').src = itemData.productImage;
      } catch (e) {}
      try {
        $item('#shareProductImage').accessibility = {
          ariaLabel: itemData.productName || 'Product image',
        };
      } catch (e) {}

      // ── S3: Add to cart button ─────────────────────────────────
      try {
        const addBtn = $item('#shareAddCart');
        try { addBtn.accessibility.ariaLabel = `Add ${itemData.productName || 'item'} to cart`; } catch (e) {}

        addBtn.onClick(async () => {
          try {
            addBtn.disable();
            addBtn.label = 'Adding...';

            const { cart } = await import('wix-stores-frontend');
            const result = await cart.addToCart(itemData.productId);
            const count = result?.cart?.lineItems?.length ?? 0;

            // Update cart counter in header if present
            try { $w('#cartCount').text = String(count); } catch (e) {}
            try { $w('#cartIcon').accessibility.ariaLabel = `Cart: ${count} item${count !== 1 ? 's' : ''}`; } catch (e) {}

            addBtn.label = 'Added!';
            announce($w, `${itemData.productName || 'Item'} added to cart`);

            setTimeout(() => {
              try {
                addBtn.label = 'Add to Cart';
                addBtn.enable();
              } catch (e) {}
            }, 2000);
          } catch (err) {
            console.error('[SharedWishlist] Add to cart failed:', err);
            try {
              addBtn.label = 'Try Again';
              addBtn.enable();
              announce($w, `Could not add ${itemData.productName || 'item'} to cart. Please try again.`);
            } catch (e) {}
          }
        });
      } catch (e) {
        console.error('[SharedWishlist] Failed to wire add-to-cart for item:', itemData._id, e);
      }
    });

    // Show content
    try { $w('#shareLoadingSection').collapse(); } catch (e) {}
    try { $w('#shareContentSection').expand(); } catch (e) {}
  } catch (err) {
    console.error('[SharedWishlist] Render error:', err);
    _showError('Something went wrong loading this wishlist. Please try again.');
  }
}

// ── Internal helpers ──────────────────────────────────────────────────

function _showError(message) {
  try { $w('#shareLoadingSection').collapse(); } catch (e) {}
  try { $w('#shareContentSection').collapse(); } catch (e) {}
  try { $w('#shareErrorText').text = message; } catch (e) {}
  try { $w('#shareErrorSection').expand(); } catch (e) {}
  try { $w('#shareNoIndex').expand(); } catch (e) {}
}
